# Generated by Django 2.1.5 on 2020-12-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('current_moisture', models.IntegerField()),
                ('target_moisture', models.IntegerField()),
                ('mode', models.CharField(max_length=6)),
                ('relay_target_status', models.CharField(max_length=3)),
                ('relay_current_state', models.CharField(max_length=3)),
            ],
        ),
    ]
